// Cross-language contract: the TS canonical payload must be byte-identical to
// Python's json.dumps(payload, sort_keys=True, ensure_ascii=False,
// separators=(",", ":")) over the same bundle. canonical_expected.txt is
// generated by tinct's own EvidenceReport.canonical_bytes().
import { readFileSync } from "node:fs"
import path from "node:path"
import { describe, expect, it } from "vitest"

import { canonicalPayloadJson, parseKeepingNumberLiterals } from "@/lib/tinct/evidence"

describe("canonical bytes cross-language parity", () => {
  it("matches Python canonical_bytes() byte-for-byte", () => {
    // Literal-preserving parse: plain JSON.parse collapses 0.0 -> 0, which is
    // exactly the class of corruption this contract exists to prevent.
    const raw = parseKeepingNumberLiterals(
      readFileSync(path.join(__dirname, "fixtures", "signed_bundle.json"), "utf-8"),
    )
    const expected = readFileSync(path.join(__dirname, "fixtures", "canonical_expected.txt"), "utf-8")
    const actual = canonicalPayloadJson(raw)
    if (actual !== expected) {
      for (let i = 0; i < Math.max(actual.length, expected.length); i++) {
        if (actual[i] !== expected[i]) {
          console.log("FIRST DIFF at index", i)
          console.log("expected:", JSON.stringify(expected.slice(Math.max(0, i - 70), i + 70)))
          console.log("actual  :", JSON.stringify(actual.slice(Math.max(0, i - 70), i + 70)))
          break
        }
      }
    }
    expect(actual).toBe(expected)
  })
})
